services:
  - type: web
    name: resume-analyzer-api
    runtime: python
    rootDir: backend
    plan: free

    envVars:
      - key: FRONTEND_ORIGIN
        value: https://infosys-resume-analyzer.vercel.app/

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /

    autoDeploy: true

disk:
  sizeGB: 1